name: Tests
run-name: ${{ github.actor }} is testing CharLib

on: [push, pull_request]

jobs:

  Regression:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: "Install CharLib"
        run: |
          pip install -e .[docs]

      - name: "Run regression tests"
        run: |
          pytest

  Characterize-gf180mcu_osu_sc:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: "Install CharLib"
        run: |
          sudo apt update && sudo apt install -y libngspice0-dev
          pip install -e .[docs]

      - name: "Download gf180mcu_osu_sc"
        run: |
          pushd test/pdks/gf180mcu_osu_sc
          mkdir models
          curl https://raw.githubusercontent.com/fossi-foundation/globalfoundries-pdk-libs-gf180mcu_fd_pr/refs/heads/main/models/ngspice/sm141064.ngspice > models/sm141064.ngspice
          curl https://raw.githubusercontent.com/fossi-foundation/globalfoundries-pdk-libs-gf180mcu_fd_pr/refs/heads/main/models/ngspice/design.ngspice > models/design.ngspice
          git clone https://github.com/stineje/globalfoundries-pdk-libs-gf180mcu_osu_sc
          popd

      - name: "Characterize 9t"
        run: |
          pushd test/pdks/gf180mcu_osu_sc
          charlib run 9t.yaml -o charlib-test-gf180mcu_osu_sc_9t.nldm.lib -j16
          popd

      - name: "Characterize 12t"
        run: |
          pushd test/pdks/gf180mcu_osu_sc
          charlib run 12t.yaml -o charlib-test-gf180mcu_osu_sc_12t.nldm.lib -j16
          popd

      - name: "Upload results"
        uses: actions/upload-artifact@v4
        with:
          name: characterization-results
          path: |
            test/pdks/gf180mcu_osu_sc/charlib-test-gf180mcu_osu_sc_9t.nldm.lib
            test/pdks/gf180mcu_osu_sc/charlib-test-gf180mcu_osu_sc_12t.nldm.lib
