name: Tests
run-name: ${{ github.actor }} is testing CharLib

on:
  - push
  - pull_request

env:
  MOSIS_OSU035_COMMIT_HASH: b36db529c2dff117e1fbead561bf792ec866e1cb
  GF180MCU_OSU_SC_COMMIT_HASH: 8a2f58f283a2eaa725314c9e1b8b7d1d343f23a3
  GF180MCU_FD_PR_COMMIT_HASH: 4adc3a4704fbe722bdf2145341a409b6419788fd

jobs:

  Regression:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: "Install CharLib"
        run: |
          pip install -e .[docs]

      - name: "Run regression tests"
        run: |
          ./test/examples/get_osu350.sh
          ./test/examples/get_gf180mcu_osu_9t.sh
          pytest

  Characterize-osu035:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: "Install Charlib"
        run: |
          sudo apt update && sudo apt install -y libngspice0-dev
          pip install -e .

      - name: "Download osu035 cells"
        run: |
          pushd test/pdks/osu350
          mkdir spice
          curl -s https://raw.githubusercontent.com/stineje/MOSIS_SCMOS/$MOSIS_OSU035_COMMIT_HASH/latest/cadence/lib/ami035/signalstorm/osu035_stdcells.sp > spice/osu035_stdcells.sp
          mkdir models
          curl -s https://raw.githubusercontent.com/stineje/MOSIS_SCMOS/$MOSIS_OSU035_COMMIT_HASH/latest/cadence/lib/ami035/lib/ami035.m > models/ami035.m
          patch models/ami035.m fix_hspice_models.patch
          popd

      - name: "Characterize"
        run: |
          pushd test/pdks/osu350
          charlib run osu350.yml -o charlib-test-osu035.nldm.lib -j16
          popd

      - name: "Upload results"
        uses: actions/upload-artifact@v7
        with:
          name: osu035-results
          path: |
            test/pdks/osu350/charlib-test-osu035.nldm.lib

  Characterize-gf180mcu_osu_sc:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: "Install CharLib"
        run: |
          sudo apt update && sudo apt install -y libngspice0-dev
          pip install -e .

      - name: "Download gf180mcu_osu_sc"
        run: |
          pushd test/pdks/gf180mcu_osu_sc
          mkdir models
          curl -s https://raw.githubusercontent.com/fossi-foundation/globalfoundries-pdk-libs-gf180mcu_fd_pr/$GF180MCU_FD_PR_COMMIT_HASH/models/ngspice/sm141064.spice > models/sm141064.spice
          curl -s https://raw.githubusercontent.com/fossi-foundation/globalfoundries-pdk-libs-gf180mcu_fd_pr/$GF180MCU_FD_PR_COMMIT_HASH/models/ngspice/design.spice > models/design.spice
          git clone https://github.com/stineje/globalfoundries-pdk-libs-gf180mcu_osu_sc
          pushd globalfoundries-pdk-libs-gf180mcu_osu_sc
          git checkout $GF180MCU_OSU_SC_COMMIT_HASH
          popd
          popd

      - name: "Characterize 9t (excluding sequential)"
        run: |
          pushd test/pdks/gf180mcu_osu_sc
          charlib run 9t.yaml -o charlib-test-gf180mcu_osu_sc_9t_comb.nldm.lib -j4 -f add and aoi buf inv mux nand nor oai or xnor xor
          popd

      - name: "Characterize 9t (sequential only)"
        run: |
          pushd test/pdks/gf180mcu_osu_sc
          charlib run 9t.yaml -o charlib-test-gf180mcu_osu_sc_9t_seq.nldm.lib -j8 -f dff dlat
          popd

      - name: "Characterize 12t (excluding sequential)"
        run: |
          pushd test/pdks/gf180mcu_osu_sc
          charlib run 12t.yaml -o charlib-test-gf180mcu_osu_sc_12t_comb.nldm.lib -j4 -f add and aoi buf inv mux nand nor oai or xnor xor
          popd

      - name: "Characterize 12t (sequential only)"
        run: |
          pushd test/pdks/gf180mcu_osu_sc
          charlib run 12t.yaml -o charlib-test-gf180mcu_osu_sc_12t_seq.nldm.lib -j8 -f dff dlat
          popd

      - name: "Upload results"
        uses: actions/upload-artifact@v7
        with:
          name: gf180mcu_osu_sc-results
          path: |
            test/pdks/gf180mcu_osu_sc/charlib-test-gf180mcu_osu_sc_9t_comb.nldm.lib
            test/pdks/gf180mcu_osu_sc/charlib-test-gf180mcu_osu_sc_9t_seq.nldm.lib
            test/pdks/gf180mcu_osu_sc/charlib-test-gf180mcu_osu_sc_12t_comb.nldm.lib
            test/pdks/gf180mcu_osu_sc/charlib-test-gf180mcu_osu_sc_12t_seq.nldm.lib
